import type { Metadata } from "next";
import providers from "./providers";
import localFont from "next/font/local";
import "./globals.css";

const poppins = localFont({
  src: "./fonts/poppins-var.otf",
  variable: "--font-poppins",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased h-screen`}
      >
        <providers>
          {children}
        </providers>
      </body>
    </html>
  );
}
